vms/config/routes.rb
Rails.application.routes.draw do
  
  resources :offers
  resources :qualifications
  resources :locations
  resources :schedules
  resources :staffs
  resources :shifts
  resources :calendars
  devise_for :users
  root 'pages#home'
  resources :positions
  resources :events
  resources :users
  get 'calendar_events' => 'events#calendar_events'    
  get 'listing' => 'events#listing'

end

vms/app/models/event.rb
class Event < ActiveRecord::Base
  #include IceCube
  
  belongs_to :calendar
  belongs_to :location, :foreign_key => :default_location
  has_many :staffs
  has_many :schedules, through: :staffs
  #has_many :users, through: {:schedules => :offers} ??   
    
  validates :name, :presence => true
  #validates :schedule_yaml, :presence => true
  validates :calendar_id, :presence => true

  scope :calendar, -> (calendar_id) { where calendar_id: calendar_id }
  scope :recurring, -> { where.not(schedule_yaml: '')}

  def recurring_rule=(ruleHash)
    if ruleHash.match("{}") then
        self.schedule_yaml = IceCube::Schedule.new.to_yaml
    end  
    if RecurringSelect.is_valid_rule?(ruleHash) then
      #Rails.logger.debug("recurring_rule= self #{self.inspect}")
      ics = IceCube::Schedule.new
      ics.start_time = self.open_time
      ics.start_date = self.open_time
      rule = RecurringSelect.dirty_hash_to_rule(ruleHash)
      #Rails.logger.debug("recurring_rule= rule #{rule.inspect}")
      ics.add_recurrence_rule(rule)
      #Rails.logger.debug("recurring_rule= ics #{ics.inspect}")
      self.schedule_yaml = ics.to_yaml
    end  
  end
  
  def recurring_schedule
    if self.schedule_yaml.nil? then
      #Rails.logger.debug("recurring_schedule setting schedule to nil")
      return IceCube::Schedule.new
    else
      #Rails.logger.debug("recurring_schedule schedule_yaml #{schedule_yaml.inspect}")
      value = IceCube::Schedule.from_yaml(self.schedule_yaml)
      #Rails.logger.debug("value #{value.inspect}")
      return value
    end
  end  
  
  def recurring_rule
    #Rails.logger.debug("recurring_rule #{self.inspect}")
    if self.schedule_yaml.nil? then
      #Rails.logger.debug("setting schedule to nil")
      return IceCube::Schedule.new
    else
      #Rails.logger.debug("recurring_rule schedule_yaml #{schedule_yaml.inspect}")
      value = IceCube::Schedule.from_yaml(self.schedule_yaml)
      #Rails.logger.debug("recurring_rule value #{value.inspect}")
      rule = value.recurrence_rules.first
      #Rails.logger.debug("recurring_rule rule #{rule.inspect}")      
      return rule.to_hash 
    end
  end
    
  def calendar_item(date_start, date_end)
    items = Array.new
    IceCube::Schedule.from_yaml(self.schedule_yaml).occurrences_between(date_start.to_time, date_end.to_time).each do |date|
      #Rails.logger.debug("calendar_item date #{date.inspect}")
      item = { 
          title: name, 
          date: date,
          url: Rails.application.routes.url_helpers.event_path(self),
          color: self.calendar.color,
          start: date,
          end:  date + self.duration.minutes,
          event_id: id,
          textColor: "black"                                       
        }
      #Rails.logger.debug("calendar_itme item #{item.inspect}")
     items << item    
    end
    #Rails.logger.debug("calendar_item items #{items.inspect}")
    return items    
    
  end   

  def listing_item(date_start, date_end)
    items = Hash.new
    IceCube::Schedule.from_yaml(self.schedule_yaml).occurrences_between(date_start.to_time, date_end.to_time).each do |date|
      Rails.logger.debug("listing_item date #{date.inspect}")
      item = { 
          title: name, 
          date: date,
          start: date,
          end:  date + self.duration.minutes,
          event_id: id,
          event: self                                       
        }
      Rails.logger.debug("listing_itme item #{item.inspect}")
     items[date.to_date] = Array.new if items[date].nil?
     items[date.to_date] << item    
    end
    Rails.logger.debug("listing_item items #{items.inspect}")
    return items    
    
  end 
        
  def non_recurring_rule; 1; end
end

vms/app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => :calendar_events
  respond_to :html, :json

  def index
     @events = Event.all
    respond_to do |format|
      format.html { respond_with @events }
      format.json { render json: @events }
    end    
  end

  def calendar_events
    if params[:calendar_ids] == 'empty' then
      respond_to do |format|
        format.json { render json: [] }
      end
    else
      # expects to have a start and end date passed
      if params[:start].present? and params[:end].present? then
        @events = Event.where(nil)
        @events = @events.where(:calendar_id => params[:calendar_ids].split(',')) if params[:calendar_ids].present?
        @dates = @events.collect { |event|  event.calendar_item(params[:start], params[:end]) }.flatten()
        respond_to do |format|
          format.json { render json: @dates }
        end
      else
        @event = Event.new
        @event.errors.add(:base, "calendar_events requires :start and :end parameters")
        Rails.logger.debug("calendar_events requires :start and :end parameters #{@event.inspect}")
        respond_to do |format|
          format.json { render :json => { :errors => @event.errors.full_messages }, :status => 422 }
        end
      end
    end    
  end

  def listing
    start_date = Time.now
    end_date = start_date + 30.days
    @events = Event.where(nil)
    @events = @events.where(:calendar_id => params[:calendar_ids].split(',')) if params[:calendar_ids].present?
    @listings = Hash.new
    @list_items = Array.new
    @events.each do |event|  
      l = event.listing_item(start_date, end_date)
      @list_items << l
      Rails.logger.debug("\n l in events loop #{l.inspect}\n") 
    end
    @listings = @events.collect { |event| event.listing_item(start_date, end_date) }.inject({}) { |a,b| a.merge(b) { |_,x,y| [*x,*y] } }
  
    respond_to do |format|
      format.html { respond_with @listings }
      format.json { render json: @listings }
    end
  end

  def show
  end

  def new
    respond_with(@event)
  end

  def edit
  end

  def create
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }      
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @event.destroy
        format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity}
      end
    end
  end

  private

    def event_params
      params.require(:event).permit(:id, :name, :abbv, :open_time, :duration, :default_location, :recurring_rule, :calendar_id)
    end
end

vms/app/helpers/events_helper.rb
module EventsHelper
end

vms/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbv %><br>
    <%= f.text_field :abbv %>
  </div>
  <div class="field">
    <%= f.label :open_time %><br>
    <%= f.time_field :open_time, :ignore_date => true %>
  </div>
  <div class="field">
    <%= f.label :calendar_id %><br>
    <%= f.collection_select :calendar_id, Calendar.order(:name), :id, :name %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :default_location %><br>
    <%= f.number_field :default_location %>
  </div>
  
  <p>
    <%= f.label :recurring_rule, "Event Recurrence Schedule" %><br/>
    <%= f.select_recurring :recurring_rule, [ ["No recurring", "{}"]], :allow_blank => true %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vms/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

vms/app/views/events/index.html.erb
 <h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbv</th>
      <th>Open Time</th>
      <th>Duration</th>
      <th>Calendar</th>
      <th>Default location</th>
      <th>Recurring Schedule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.abbv %></td>
        <td><%= event.open_time.strftime("%I:%M %p") %></td>
        <td><%= event.duration %></td>
        <td><%= event.calendar.name %></td>
        <td><%= event.default_location %></td>
        <td><%= event.recurring_schedule.to_s %></td>
        <td><%= link_to 'Show', event_path(event) %></td>
        <td><% if can?(:edit, event) %><%= link_to 'Edit', edit_event_path(event) %><% end %></td>
        <td><% if can?(:destroy, event) %><%= link_to 'Destroy',  event_path(:id => event.id) , method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can?(:create, Event) %><%= link_to 'New Event', new_event_path %><% end %>

vms/app/views/events/listing.html.erb
 <h1>Listing events</h1>
<%  order = @listings.keys.sort %>
<%  order.each do |date| %>
  <div style="background: yellow;"><b><%= date %></b></div>
  <% @listings[date].each do |event| %>
      <% e = event[:event] %>
      <% schedules = Schedule.where(staff_id: e.staffs.map(&:id), date: event[:date].to_time) %>
      <div><b><%= event[:title] %></b></div>
      <table>
        <thead>
        <th></th>
        <th><u>STAFF</u></th>
        <th><u>START</u></th>
        <th><u>END</u></th>
        <th><u>VOLUNTEER</u></th>
        <th><u>Click below to:</u></th>
        <th><u>SHADOWS</u></th>
        <th><u>Click below to:</u></th>
        </thead>
        <tbody>        
      
      <% schedules.each do |s| %>
      <tr>
        <td></td>
        <td><%= s.position.name %></td>
        <td><%= s.shift.start %></td>
        <td><%= s.shift.duration.to_i %></td>
        <td><%= s.accepted_offer.user.username if s.accepted_offer %></td>
        <td><%= if s.accepted_offer then 
                  link_to('Cancel shift', s.accepted_offer, method: :delete, data: { confirm: 'Are you sure?' }) 
                else 
                  link_to('Sign up', new_offer_path(schedule_id: s.id))
                end  
            %>
        </td>
      </tr>
      <% end %>
      </tbody>
      </table>
    <% end %>   
  <% end %>
<br>

<% if can?(:create, Event) %><%= link_to 'New Event', new_event_path %><% end %>

vms/app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

vms/app/views/events/show.html.erb
<table>
<tr>
<td>
  <strong>Name:</strong>
  <%= @event.name %>
</td>
<td>
  <strong>Abbv:</strong>
  <%= @event.abbv %>
</td>
</tr>
<tr>
<td>
  <strong>Calendar:</strong>
  <%= @event.calendar.name %>
</td>
<td>
  <strong>Default location:</strong>
  <%= @event.location.name %>
</td>
</tr>
<tr>
<td>
  <strong>Open Time:</strong>
  <%= @event.open_time.strftime("%I:%M %p") %>
</td>
<td>
  <strong>Close Time:</strong>
  <%= (@event.open_time+ @event.duration.minutes).strftime("%I:%M %p") %>
</td>
<td>
  <strong>Duration:</strong>
  <%= @event.duration %>
</td>
</tr>
</table>

<% if can?(:edit, @event) %><%= link_to 'Edit', edit_event_path(@event) %> |<% end %>
<%= link_to 'Back', events_path %>