vms/config/routes.rb
Rails.application.routes.draw do
  
  resources :offers
  resources :qualifications
  resources :locations
  resources :schedules
  resources :staffs
  resources :shifts
  resources :calendars
  devise_for :users
  root 'pages#home'
  resources :positions
  resources :events
  resources :users
  get 'calendar_events' => 'events#calendar_events'    
  get 'listing' => 'events#listing'

end

vms/app/models/calendar.rb
class Calendar < ActiveRecord::Base
  has_many :events
  validates :name, :description, :color, :presence => true
  validates_format_of :color, with: /\A#?(?:[A-F0-9]{3}){1,2}\z/i,
      message: "%{value} must be a hex RGB color (#xxXXxx).  Ex: #940a3b"
end

vms/app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @calendars = Calendar.all
    respond_to do |format|
      format.html { respond_with @calendars }
      format.json { render json: @calendars }
    end    
  end
  


  def show
    respond_with(@calendar)
  end

  def new
    @calendar = Calendar.new
    respond_with(@calendar)
  end

  def edit
  end

  def create
    authorize! :create, Calendar
    @calendar = Calendar.new(calendar_params)
    @calendar.save
    respond_with(@calendar)
  end

  def update
    authorize! :update, Calendar
    @calendar.update(calendar_params)
    respond_with(@calendar)
  end

  def destroy
    authorize! :destroy, Calendar
    @calendar.destroy
    respond_with(@calendar)
  end

  private
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    def calendar_params
      params.require(:calendar).permit(:name, :description, :color)
    end
end

vms/app/helpers/calendars_helper.rb
module CalendarsHelper
end

vms/app/views/calendars/_form.html.erb
<%= form_for(@calendar) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color, as: :minicolors, id: 'calendar-color', input_html: {data: {
          minicolors: {theme: :bootstrap, position: :right}}} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vms/app/views/calendars/_list.html.erb
<h1>Listing calendars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calendars.each do |calendar| %>
      <tr>
        <td><%= calendar.name %></td>
        <td><%= calendar.description %></td>
        <td><div style="background-color: <%= calendar.color %>;" class="color-box"></div><%= calendar.color %></td>
        <td><%= link_to 'Show', calendar %></td>
        <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
        <td><%= link_to 'Destroy', calendar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calendar', new_calendar_path %>

vms/app/views/calendars/_picker.html.erb
<ul>
<% @calendars.each do |c| %>
  <li>
    <span style="background-color: <%= c.color %>;">
      <%= check_box_tag 'show_calendar_'+c.id.to_s, value=c.id.to_s, checked=true, 
          :onchange => "toggleCalendar(this,"+c.id.to_s+ ");", 
          :class => "visible_calendars" %>
    </span>                                                                                                                                               
    <%= c.name %>
    <%= link_to 'x', calendar_path(c), :confirm => "Are you sure you want to remove the calendar?", :method => :delete %></li>
<% end %>

vms/app/views/calendars/edit.html.erb
<h1>Editing calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

vms/app/views/calendars/index.html.erb
<div>
  <div id="calendar-div">
    <h4>Currently: <%= Time.now.strftime("%v %r") %></h4>
    <div id="calendar" class="fc"></div>
  </div>
  <div id="sidebar">
    <%= render 'picker' %>
  </div>
</div>
<div id="list">
 <%= render "list" %>
</div>

vms/app/views/calendars/new.html.erb
<h1>New calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>

vms/app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @calendar.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @calendar.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @calendar.color %>
</p>

<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>