vms/config/routes.rb
Rails.application.routes.draw do
  
  resources :offers
  resources :qualifications
  resources :locations
  resources :schedules
  resources :staffs
  resources :shifts
  resources :calendars
  devise_for :users
  root 'pages#home'
  resources :positions
  resources :events
  resources :users
  get 'calendar_events' => 'events#calendar_events'    
  get 'listing' => 'events#listing'

end

vms/app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
  belongs_to :schedule
end

vms/app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @offers = Offer.all
    respond_with(@offers)
  end

  def show
    respond_with(@offer)
  end

  def new
    @offer = Offer.new
    respond_with(@offer)
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.save
    respond_with(@offer)
  end

  def update
    @offer.update(offer_params)
    respond_with(@offer)
  end

  def destroy
    @offer.destroy
    respond_with(@offer)
  end

  private
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:user_id, :schedule_id, :accepted)
    end
end

vms/app/helpers/offers_helper.rb
module OffersHelper
end

vms/app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= current_user.username %>
  </div>
  <div class="field">
    <%= f.label :schedule_id %><br>
    <%= f.collection_select :schedule_id, Schedule.all, :id, :info, {:selected => params[:schedule_id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vms/app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

vms/app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Schedule</th>
      <th>Accepted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.user %></td>
        <td><%= offer.schedule %></td>
        <td><%= offer.accepted %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

vms/app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

vms/app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @offer.user %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @offer.schedule %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @offer.accepted %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>