vms/config/routes.rb
Rails.application.routes.draw do
  
  resources :offers
  resources :qualifications
  resources :locations
  resources :schedules
  resources :staffs
  resources :shifts
  resources :calendars
  devise_for :users
  root 'pages#home'
  resources :positions
  resources :events
  resources :users
  get 'calendar_events' => 'events#calendar_events'    
  get 'listing' => 'events#listing'

end

vms/app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :event
  belongs_to :position
  belongs_to :shift
  has_many :schedules
end

vms/app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @staffs = Staff.all
    respond_with(@staffs)
  end

  def show
    respond_with(@staff)
  end

  def new
    @staff = Staff.new
    respond_with(@staff)
  end

  def edit
  end

  def create
    @staff = Staff.new(staff_params)
    @staff.save
    respond_with(@staff)
  end

  def update
    @staff.update(staff_params)
    respond_with(@staff)
  end

  def destroy
    @staff.destroy
    respond_with(@staff)
  end

  private
    def set_staff
      @staff = Staff.find(params[:id])
    end

    def staff_params
      params.require(:staff).permit(:event_id, :position_id, :shift_id, :permanent_user)
    end
end

vms/app/helpers/staffs_helper.rb
module StaffsHelper
end

vms/app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.collection_select :staff, :event_id, Event.order(:name), :id, :name %>
  </div>
  <div class="field">
    <%= f.label :position_id %><br>
    <%= f.text_field :position_id %>
  </div>
  <div class="field">
    <%= f.label :shift_id %><br>
    <%= f.text_field :shift_id %>
  </div>
  <div class="field">
    <%= f.label :permanent_user %><br>
    <%= f.number_field :permanent_user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vms/app/views/staffs/edit.html.erb
<h1>Editing staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

vms/app/views/staffs/index.html.erb
<h1>Listing staffs</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Role</th>
      <th>Shift</th>
      <th>Permanent user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.event.name %></td>
        <td><%= staff.position.name %></td>
        <td><%= staff.shift.start %></td>
        <td><%= staff.permanent_user %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

vms/app/views/staffs/new.html.erb
<h1>New staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

vms/app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @staff.event %>
</p>

<p>
  <strong>Position:</strong>
  <%= @staff.position %>
</p>

<p>
  <strong>Shift:</strong>
  <%= @staff.shift %>
</p>

<p>
  <strong>Permanent user:</strong>
  <%= @staff.permanent_user %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>